### ISSUE TITLE
Problem with cmake

### ISSUE THREAD

**Issue by daniele-baccega** [FLAMEGPU/FLAMEGPU2#1038] opened 2023-02-10 13:43 UTC
I have a problem when I run the command **cmake --build . --target all -j 8** on the "FLAMEGPU2-model-templace-cpp".
In particular I obtain the error that you can see in the screenshot.

![Screenshot from 2023-02-10 14-36-12](https://user-images.githubusercontent.com/94167431/218105630-f4a23257-014b-45c8-8c1a-4820be3be972.png)

**Configuration:**
 - OS: Ubuntu 20.04.5 LTS
 - CUDA version: 11.4.315
 - GPU NVIDIA Tegra Xavier (nvgpu)/integrated

How can I solve it? If I remove that if and the subsequent return statement, the error gone.
Thank you

**Comment by Robadob** [comment] 2023-02-10 13:47
It appears to be a compilation issue rather than CMake. Which version of g++ are you using?

**Comment by daniele-baccega** [comment] 2023-02-10 13:49
I'm using g++ 9.4.0

**Comment by Robadob** [comment] 2023-02-10 13:58
Thanks, that should be fine by my understanding.
@ptheywood's the Linux expert of the team, I think he'll be able to provide comment when he's back from lunch.

**Comment by ptheywood** [comment] 2023-02-10 15:02
With GCC 9.4.0 & nvcc 11.4.152 on a Ubuntu 20.04.5 machine with an intel x86_64 cpu I'm unable to reproduce the issue with the current `master` branch of the main FLAMEGPU2 repository.  

Best guess is that there is a subtle difference in the gcc or glibc build for arm hosts compared to x86_64.

`va_list` seems to be an unspecified typedef (so implementation defined), and then there would be no guarantee that it is covnertable to bool.

We don't currently have a tegra system set up to be able to check this ourselves (we may have a TX2 in the office cupboard though I have a feeling it found a new home).

The simplest (probably) fix is for the `if(!argp)` early return to be removed, but we may need to add some tests to ensure that it behaves well without a format string being passed. 

We can put that together into a branch for you to try, but we won't be able to know if that actually fixes the problem for you or not until you try it.

**Comment by Robadob** [comment] 2023-02-10 18:28
Resolved by #1039, fix agrees with original post's observation.

**Closed by Robadob** 2023-02-10 18:28 UTC
Labels: bug

**Comment by daniele-baccega** [comment] 2023-02-24 10:07
Thank you very much!

I obtained the same error in an other file related to the visualization:
![screen](https://user-images.githubusercontent.com/94167431/221151235-65014e28-74ef-45e7-bef4-6298b1aab643.png)

Thanks again!

**Comment by Robadob** [comment] 2023-02-24 10:45
Thanks, I'll get this addressed today.
