### ISSUE TITLE
Memory leak caused by RTC compilation.

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#756] opened 2021-12-16 13:29 UTC
There appears to be a memory leak somewhere within the RTC compilation process.

This was found by @MILeach when running the [concurrency benchmark](https://github.com/flamegpu/FLAMEGPU2-concurrency-benchmark) on local HPC with a 10GB(?) memory limit (which be more than enough).

The benchmark is essentially the boids RTC implementations, but with multiple independent species of boid existing at the same time, which do no interact with one another. 

The current RTC implementation of curve requires that each concurrent speices requires its own RTC compilation for each agent function, even though the actual source is the same. 

The current benchmarks include up to 127 species for spatial and brute force implementations, each containing 2 agent functions, so 508 RTC compilations would occur in total (if no previous runs had been performed). 

As each RTC function is compiled, the memory footprint of the application grows. To test this locally without waiting a significant length of time, I modified the benchmark above to:

+ Only execute a single step
+ Only run a single repetition
+ remove the iteration of messages in agent functions, to speed up the simulation steps.
+ Only run the `largePopsFalloff` benchmark, from `127` to `127` species 
  + a much smaller configuraiton would also highlight this
+ Cleared my local RTC cache
+ Ran the benchmark watching the virtual and resident memory use via `htop`.

As each sequential RTC compile occurred (and new agent data was generated on the host), the memory footprint grew, ending up over 13GB of resident memory and over 16GB of virtual. 
On a re-run of the benchmark which loads rtc functions from an on-disk cache, only ~1GB of resident memory was required, with ~6GB of virtual.

A smaller run with only 8 species (16 RTC compiles) uses over 1GB of host memory when RTC compilation occurs, but less than 240MB when the rtc/jitify cache is hit.

This memory does not appear to be released when it is no longer required (i.e. after RTC compilation has finished, or when a `CudaSimulation` goes out of scope), even though each RTC compilation phase is independent. Ideally any memory required by this process should be freed once it is no longer required.

This leak could be in NVRTC, Jitify or in our use of NVRTC/Jitify. I have not investigated the actual cause. It is either not being free'd until application destruction, or at all.

**Comment by Robadob** [comment] 2021-12-16 13:33
There is an in memory JitifyCache, which stores a copy of every RTC compilation performed/loaded.

We already know ensemble doesn't use the cache properly, so could it be that?

**Comment by ptheywood** [comment] 2021-12-16 14:30
Valgrind output logs + patch from running with 4 pops, with and without a cache hit. 

Key summaries are:

Cache Miss:
```
==37357== LEAK SUMMARY:
==37357==    definitely lost: 43,424 bytes in 352 blocks
==37357==    indirectly lost: 338,302,481 bytes in 29,137 blocks
==37357==      possibly lost: 90,922,719 bytes in 298 blocks
==37357==    still reachable: 19,758,827 bytes in 13,240 blocks
==37357==         suppressed: 0 bytes in 0 blocks
```

Cache hit:

```
==42621== LEAK SUMMARY:
==42621==    definitely lost: 0 bytes in 0 blocks
==42621==    indirectly lost: 0 bytes in 0 blocks
==42621==      possibly lost: 22,552 bytes in 195 blocks
==42621==    still reachable: 19,755,889 bytes in 13,232 blocks
==42621==         suppressed: 0 bytes in 0 blocks
```

https://gist.github.com/ptheywood/e4e2cc41f00e20f3f886a7cf4e0c766d

**Comment by ptheywood** [comment] 2021-12-16 15:45
Valgrinding the `matrixMul_nvrtc` cuda sample does not report any leaks via `nvrtcCreateProgram` as we encounter above.

Valgrinding the jitify example program however does (once patched to not throw an exception) although it is significantly smaller. 

https://gist.github.com/ptheywood/ca81e19dd8fe79e75ae3269014389009

Running the modified concurrency benchmark above using CUDA 11.5 rather than CUDA 11.2 still leaks as above. Summary below but not the full log:

```
==72132== LEAK SUMMARY:
==72132==    definitely lost: 58,624 bytes in 480 blocks
==72132==    indirectly lost: 454,449,398 bytes in 49,696 blocks
==72132==      possibly lost: 83,313,394 bytes in 315 blocks
==72132==    still reachable: 19,500,910 bytes in 11,791 blocks
==72132==         suppressed: 0 bytes in 0 blocks
```

**Comment by Robadob** [comment] 2022-01-28 10:38
There's now a fix for this, it was caused by Jitify. https://github.com/NVIDIA/jitify/pull/93

Once that has been merged, will need to update out pinned Jitify commit ([here](https://github.com/FLAMEGPU/FLAMEGPU2/blob/e086df5bb72e541ea62e4bffe975ca6dc259d952/cmake/dependencies/Jitify.cmake#L13))

**Closed** 2022-01-28 19:42 UTC
Labels: bug, RTC
